//! Helpers shared by .NET / C# analyzers.
//!
//! `.csproj` and `.sln` are XML-like text files. Rather than wire in
//! an XML parser for one-off attribute lookups we use line-based
//! regex — same pragmatic shortcut as Gradle/Composer.

use std::path::Path;

use once_cell::sync::Lazy;
use regex::Regex;

use super::super::super::traits::DetectedFramework;

/// Match `<PackageReference Include="X.Y.Z" ...>` lines in a .csproj.
static RE_PACKAGE_REF: Lazy<Regex> = Lazy::new(|| {
    Regex::new(r#"<PackageReference\s+Include="([A-Za-z0-9._\-]+)""#).unwrap()
});

/// Match the `Sdk="..."` attribute on the `<Project>` element of a
/// modern (SDK-style) .csproj.
static RE_SDK_ATTR: Lazy<Regex> = Lazy::new(|| {
    Regex::new(r#"<Project\s+Sdk="([A-Za-z0-9._\-/]+)""#).unwrap()
});

/// Locate the first `.csproj` or `.sln` at the project root. Returns
/// `(file_name, kind)` where `kind` is `"csproj"` or `"sln"`.
pub fn find_dotnet_marker(project_root: &Path) -> Option<(String, &'static str)> {
    let mut csproj: Option<String> = None;
    let mut sln: Option<String> = None;
    if let Ok(entries) = std::fs::read_dir(project_root) {
        for entry in entries.flatten() {
            let name = match entry.file_name().to_str() {
                Some(s) => s.to_string(),
                None => continue,
            };
            if name.ends_with(".csproj") && csproj.is_none() {
                csproj = Some(name);
            } else if name.ends_with(".sln") && sln.is_none() {
                sln = Some(name);
            }
        }
    }
    csproj
        .map(|n| (n, "csproj"))
        .or(sln.map(|n| (n, "sln")))
}

/// Read the textual content of the first `.csproj` at the project
/// root. Returns `None` when none exists or read fails.
pub fn read_first_csproj(project_root: &Path) -> Option<String> {
    if let Ok(entries) = std::fs::read_dir(project_root) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path
                .extension()
                .and_then(|e| e.to_str())
                .map(|e| e == "csproj")
                .unwrap_or(false)
            {
                return std::fs::read_to_string(&path).ok();
            }
        }
    }
    None
}

/// Extract the SDK attribute of a .csproj (`Microsoft.NET.Sdk`,
/// `Microsoft.NET.Sdk.Web`, etc.). Returns `None` for legacy
/// non-SDK-style projects.
pub fn get_sdk(csproj_text: &str) -> Option<String> {
    RE_SDK_ATTR
        .captures(csproj_text)
        .and_then(|c| c.get(1))
        .map(|m| m.as_str().to_string())
}

/// Detect .NET frameworks from a .csproj's textual content.
///
/// Today catches ASP.NET via `Microsoft.NET.Sdk.Web` SDK and
/// Unity via `UnityEngine` references. (Unity proper is detected
/// filesystem-level — see [`is_unity_project`] — because Unity-generated
/// `.csproj` files are auto-rewritten on import and not always
/// reliable.)
pub fn detect_frameworks_from_csproj(csproj_text: &str) -> Vec<DetectedFramework> {
    let mut frameworks = Vec::new();

    if let Some(sdk) = get_sdk(csproj_text) {
        if sdk.eq_ignore_ascii_case("Microsoft.NET.Sdk.Web") {
            frameworks.push(DetectedFramework::AspNet);
        }
    }

    for cap in RE_PACKAGE_REF.captures_iter(csproj_text) {
        let Some(pkg) = cap.get(1) else { continue };
        let pkg = pkg.as_str();
        // ASP.NET is also signalled by Microsoft.AspNetCore.* packages
        // (older targets that don't use the Web SDK).
        if pkg.starts_with("Microsoft.AspNetCore")
            && !frameworks.contains(&DetectedFramework::AspNet)
        {
            frameworks.push(DetectedFramework::AspNet);
        }
    }

    frameworks
}

/// Filesystem-level Unity check.
///
/// Unity projects always ship `ProjectSettings/ProjectVersion.txt`
/// (the engine writes it on save) and an `Assets/` directory.
/// `.csproj` files in Unity projects are autogenerated by the
/// editor and not always reliable, so we check the canonical layout
/// directly.
pub fn is_unity_project(project_root: &Path) -> bool {
    project_root
        .join("ProjectSettings")
        .join("ProjectVersion.txt")
        .exists()
        && project_root.join("Assets").is_dir()
}
