//! Context generation module
//!
//! Handles writing and managing .context.md files generated by LLMs.

pub mod types;
pub mod frontmatter;
pub mod prompts;
pub mod writer;
pub mod hash;
pub mod hash_storage;
pub mod cache;
pub mod repository;
pub mod file_storage;

// Re-exports from types
pub use types::{
    ContextMetadata, ModuleIdentity, ModuleType, ModuleStatus,
    Layer, LayerType, LayerStatus,
    Connection, ConnectionType, Dependencies,
    Deployment, EnvVar, PerformanceTarget,
    Quality, ComplexityScore, SecurityAudit,
    Versioning, BreakingChange, Deprecation, RoadmapItem, Priority,
    AgentContext, AgentScope, ComplexityLevel, SuggestedAgent,
    GenerationMetadata,
    DepthLevel, GenerationConfig,  // ← NUEVO
};

// Re-exports from writer
pub use writer::{ContextWriter, WriteOptions};

// Re-exports from hash
pub use hash::{calculate_code_hash, is_context_stale};

// Re-exports from cache
pub use cache::{HashCache, CacheEntry};

// Re-exports from frontmatter (for reading)
pub use frontmatter::FrontmatterBuilder;

// Re-exports from prompts
pub use prompts::ContextPromptBuilder;

// Re-exports from repository
pub use repository::{ContextRepository, ModuleContextRecord, ModuleLayerRecord};
