//! # Batch Context Generation
//!
//! Core business logic for generating contexts in batch.
//! This module contains ALL orchestration logic.
//!
//! ## Design:
//! - Receives configuration struct with all inputs
//! - Uses callback functions for progress/completion events
//! - Handles checkpoint save/load, pause/resume, rate limiting
//! - Clients (Desktop, API, CLI) provide callbacks for their specific needs
//!
//! ## Usage:
//! ```rust,ignore
//! use venore_core::wizard::batch_generation::*;
//!
//! let config = BatchGenerationConfig { ... };
//!
//! generate_batch_contexts(
//!     config,
//!     |event| { /* handle progress */ },
//!     |event| { /* handle completion */ },
//! ).await?;
//! ```

use crate::analysis::AnalysisOutput;
use crate::checkpoint::{CheckpointManager, WizardConfig};
use crate::context::{
    ContextMetadata, ModuleIdentity, ModuleType, ModuleStatus,
    Dependencies, GenerationMetadata, FrontmatterBuilder,
    calculate_code_hash, DepthLevel,
};
use crate::llm::prelude::*;
use crate::wizard::{BatchManager, WizardEventEmitter, CallbackEventEmitter};
use crate::{VenoreError, Result};
use std::path::PathBuf;
use std::sync::Arc;
use std::sync::atomic::Ordering;
use std::time::Instant;

// =============================================================================
// Configuration
// =============================================================================

/// Configuration for batch context generation
#[derive(Debug, Clone)]
pub struct BatchGenerationConfig {
    /// Batch ID (generated by BatchManager)
    pub batch_id: String,

    /// Absolute path to project root
    pub project_path: PathBuf,

    /// Module IDs to generate (remaining, not all selected)
    pub module_ids: Vec<String>,

    /// Module paths (relative to project_path, parallel to module_ids)
    pub module_paths: Vec<String>,

    /// LLM model to use
    pub model: String,

    /// LLM provider
    pub provider: LlmProviderType,

    /// Depth level for context generation
    pub depth_level: DepthLevel,

    /// System prompt for context generation (resolved from prompt registry)
    pub system_prompt: String,

    /// Full analysis output (from module detection step)
    pub analysis: AnalysisOutput,

    /// Wizard configuration (for checkpoint)
    pub wizard_config: WizardConfig,

    /// Total selected modules (for global progress tracking)
    pub total_selected: usize,

    /// Previously completed count (from checkpoint)
    pub previously_completed: usize,
}

// =============================================================================
// Events
// =============================================================================

/// Progress event for a single module
#[derive(Debug, Clone)]
pub struct ProgressEvent {
    /// Batch ID
    pub batch_id: String,

    /// Current module index (global, including previously completed)
    pub current: usize,

    /// Total modules to generate
    pub total: usize,

    /// Module ID being processed
    pub module_id: String,

    /// Status: "running", "completed", "failed"
    pub status: String,

    /// Tokens used (if completed)
    pub tokens_used: usize,

    /// Error message (if failed)
    pub error: Option<String>,
}

/// Completion event for entire batch
#[derive(Debug, Clone)]
pub struct CompleteEvent {
    /// Batch ID
    pub batch_id: String,

    /// Number of modules completed successfully
    pub total_completed: usize,

    /// Number of modules that failed
    pub total_failed: usize,

    /// Total duration in milliseconds
    pub duration_ms: u64,
}

/// Result of batch generation
#[derive(Debug, Clone)]
pub struct BatchGenerationResult {
    /// Number of modules completed successfully
    pub completed: usize,

    /// Number of modules that failed
    pub failed: usize,

    /// Total duration in milliseconds
    pub duration_ms: u64,
}

// =============================================================================
// Batch Generation Logic
// =============================================================================

/// Generate contexts for a batch of modules (callback-based API)
///
/// This is a backward-compatible wrapper around `generate_batch_contexts_with_emitter`.
/// New code should prefer using `generate_batch_contexts_with_emitter` directly.
///
/// # Arguments
///
/// * `config` - Complete configuration for batch generation
/// * `llm_gateway` - LLM Gateway for API calls
/// * `on_progress` - Callback for progress events (called for each module)
/// * `on_complete` - Callback for completion event (called once at end)
///
/// # Returns
///
/// Returns `BatchGenerationResult` with statistics
pub async fn generate_batch_contexts<F1, F2>(
    config: BatchGenerationConfig,
    llm_gateway: Arc<LlmGateway>,
    on_progress: F1,
    on_complete: F2,
) -> Result<BatchGenerationResult>
where
    F1: Fn(ProgressEvent) + Send + Sync + 'static,
    F2: Fn(CompleteEvent) + Send + Sync + 'static,
{
    // Wrap callbacks in CallbackEventEmitter
    let emitter = Arc::new(CallbackEventEmitter::new(on_progress, on_complete));
    generate_batch_contexts_with_emitter(config, llm_gateway, emitter).await
}

/// Generate contexts for a batch of modules (event emitter-based API)
///
/// This function contains ALL orchestration logic:
/// - Checkpoint management (load/save)
/// - Pause/resume handling
/// - LLM calls with rate limiting
/// - File writing with frontmatter
/// - Event emission via WizardEventEmitter trait
///
/// # Arguments
///
/// * `config` - Complete configuration for batch generation
/// * `llm_gateway` - LLM Gateway for API calls
/// * `event_emitter` - Event emitter for progress/completion notifications
///
/// # Returns
///
/// Returns `BatchGenerationResult` with statistics
///
/// # Errors
///
/// Returns `VenoreError` if:
/// - Checkpoint operations fail critically
/// - All modules fail to generate
/// - Batch is paused and never resumed (timeout)
///
/// # Example
///
/// ```rust,ignore
/// use std::sync::Arc;
/// use venore_core::wizard::{WizardEventEmitter, NullEventEmitter};
///
/// let emitter: Arc<dyn WizardEventEmitter> = Arc::new(NullEventEmitter);
/// let result = generate_batch_contexts_with_emitter(config, gateway, emitter).await?;
/// ```
pub async fn generate_batch_contexts_with_emitter(
    config: BatchGenerationConfig,
    llm_gateway: Arc<LlmGateway>,
    event_emitter: Arc<dyn WizardEventEmitter>,
) -> Result<BatchGenerationResult>
{
    let start_time = Instant::now();
    let mut completed = 0;
    let mut failed = 0;

    tracing::info!(
        "🚀 Starting batch generation: {} remaining of {} total selected",
        config.module_ids.len(),
        config.total_selected
    );

    // 1. CHECKPOINT MANAGEMENT
    let checkpoint_manager = CheckpointManager::new(&config.project_path);

    match checkpoint_manager.load() {
        Ok(Some(_)) => {
            tracing::info!("📦 Loaded existing checkpoint (resuming)");
        }
        Ok(None) | Err(_) => {
            tracing::info!("📦 No checkpoint found, creating new one...");
            if let Err(e) = checkpoint_manager.initialize_with_wizard_config(
                config.project_path.clone(),
                config.wizard_config.clone(),
                config.total_selected,
            ) {
                tracing::error!("❌ Failed to initialize checkpoint: {}", e);
            } else {
                tracing::info!("✅ Checkpoint initialized");
            }
        }
    }

    // 2. GET BATCH STATE (for pause/resume)
    let batch_manager = BatchManager::global();
    let paused_flag = {
        let guard = batch_manager.lock().unwrap();
        guard.get_pause_flag(&config.batch_id)
            .ok_or_else(|| VenoreError::Unknown(
                format!("Batch {} not found in BatchManager", config.batch_id)
            ))?
    };

    // 3. GENERATE CONTEXTS FOR EACH MODULE
    for (i, module_id) in config.module_ids.iter().enumerate() {
        // 3.1. CHECK PAUSE FLAG (wait if paused)
        let is_paused = paused_flag.load(Ordering::Relaxed);
        if is_paused {
            tracing::info!("⏸️  Paused at module {}/{}, waiting...", i + 1, config.module_ids.len());
        }

        while paused_flag.load(Ordering::Relaxed) {
            tokio::time::sleep(tokio::time::Duration::from_millis(500)).await;
        }

        if is_paused {
            tracing::info!("▶️  Resumed from module {}/{}", i + 1, config.module_ids.len());
        }

        // 3.2. CALCULATE GLOBAL PROGRESS
        let current_global = config.previously_completed + i + 1;
        tracing::info!(
            "[{}/{}] Generating context for module: {}",
            current_global,
            config.total_selected,
            module_id
        );

        // 3.3. EMIT "RUNNING" PROGRESS
        event_emitter.emit_progress(ProgressEvent {
            batch_id: config.batch_id.clone(),
            current: current_global,
            total: config.total_selected,
            module_id: module_id.clone(),
            status: "running".to_string(),
            tokens_used: 0,
            error: None,
        });

        // 3.4. FIND MODULE ANALYSIS
        let module_path_str = &config.module_paths[i];
        let module_path = PathBuf::from(module_path_str);
        let module_name = module_path
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("unknown");

        let module_analysis = config.analysis.modules.iter()
            .find(|m| m.name == module_name);

        let module_analysis = match module_analysis {
            Some(m) => m,
            None => {
                tracing::error!("❌ Module '{}' not found in analysis", module_id);
                failed += 1;
                event_emitter.emit_progress(ProgressEvent {
                    batch_id: config.batch_id.clone(),
                    current: current_global,
                    total: config.total_selected,
                    module_id: module_id.clone(),
                    status: "failed".to_string(),
                    tokens_used: 0,
                    error: Some("Module not found in analysis".to_string()),
                });
                continue;
            }
        };

        // 3.5. BUILD PROMPT
        let prompt = build_module_prompt(module_analysis, &config.depth_level);

        // 3.6. CALL LLM
        let llm_request = LlmRequest {
            model: config.model.clone(),
            messages: vec![
                LlmMessage {
                    role: MessageRole::System,
                    content: config.system_prompt.clone(),
                    tool_call_id: None,
                    tool_calls: None,
                    content_parts: None,
                },
                LlmMessage {
                    role: MessageRole::User,
                    content: prompt,
                    tool_call_id: None,
                    tool_calls: None,
                    content_parts: None,
                },
            ],
            temperature: Some(0.3),
            max_tokens: Some(config.depth_level.max_tokens()),
            tools: None,
            json_schema: None,
            timeout_secs: Some(120),
            web_search: false,
        };

        let options = GatewayOptions::for_task(LlmTask::Onboarding)
            .with_provider(config.provider)
            .with_model(config.model.clone());

        match llm_gateway.complete(llm_request, options).await {
            Ok(response) => {
                let tokens = response.usage.as_ref().map(|u| u.total_tokens).unwrap_or(0);

                // 3.7. WRITE CONTEXT FILE
                let module_dir = config.project_path.join(module_path_str);
                let context_file = module_dir.join(".context.md");

                let metadata = build_metadata(
                    &module_analysis.name,
                    &config.model,
                    config.provider,
                    &response,
                    &module_analysis.code_snippets,
                );

                // Ensure directory exists
                if !module_dir.exists() {
                    tracing::warn!("Creating module directory: {}", module_dir.display());
                    let _ = std::fs::create_dir_all(&module_dir);
                }

                // Build content with frontmatter
                let frontmatter = match FrontmatterBuilder::build(&metadata) {
                    Ok(fm) => fm,
                    Err(e) => {
                        tracing::error!("Failed to build frontmatter: {}", e);
                        "---\n---\n".to_string()
                    }
                };

                let content = format!("{}\n\n{}", frontmatter, response.content);

                tracing::info!(
                    "Writing context file: {} (provider: {}, model: {})",
                    context_file.display(),
                    response.provider.as_str(),
                    response.model
                );

                let temp_file = context_file.with_extension("context.md.tmp");
                match std::fs::write(&temp_file, &content)
                    .and_then(|_| std::fs::rename(&temp_file, &context_file)) {
                    Ok(_) => {
                        completed += 1;
                        tracing::info!("✅ Generated context for {}: {} tokens", module_id, tokens);

                        // 3.8. UPDATE CHECKPOINT
                        if let Err(e) = checkpoint_manager.mark_completed(module_name.to_string()) {
                            tracing::error!("❌ Failed to update checkpoint: {}", e);
                        } else {
                            let total_completed_global = config.previously_completed + completed;
                            tracing::info!(
                                "✅ Checkpoint updated: {}/{} modules completed",
                                total_completed_global,
                                config.total_selected
                            );
                        }

                        // 3.9. EMIT "COMPLETED" PROGRESS
                        event_emitter.emit_progress(ProgressEvent {
                            batch_id: config.batch_id.clone(),
                            current: current_global,
                            total: config.total_selected,
                            module_id: module_id.clone(),
                            status: "completed".to_string(),
                            tokens_used: tokens as usize,
                            error: None,
                        });
                    }
                    Err(e) => {
                        failed += 1;
                        tracing::error!("❌ Failed to write context: {}", e);
                        event_emitter.emit_progress(ProgressEvent {
                            batch_id: config.batch_id.clone(),
                            current: current_global,
                            total: config.total_selected,
                            module_id: module_id.clone(),
                            status: "failed".to_string(),
                            tokens_used: 0,
                            error: Some(format!("Failed to write file: {}", e)),
                        });
                    }
                }
            }
            Err(e) => {
                failed += 1;
                tracing::error!("❌ LLM failed for {}: {}", module_id, e);
                event_emitter.emit_progress(ProgressEvent {
                    batch_id: config.batch_id.clone(),
                    current: current_global,
                    total: config.total_selected,
                    module_id: module_id.clone(),
                    status: "failed".to_string(),
                    tokens_used: 0,
                    error: Some(format!("LLM generation failed: {}", e)),
                });
            }
        }

        // 3.10. RATE LIMITING DELAY
        if i < config.module_ids.len() - 1 {
            let delay_secs = match config.provider {
                LlmProviderType::Gemini => 4,
                LlmProviderType::Anthropic => 2,
                LlmProviderType::OpenAI => 2,
                LlmProviderType::Ollama | LlmProviderType::Tavily => 0,
            };

            if delay_secs > 0 {
                tracing::info!("⏳ Waiting {}s before next module...", delay_secs);
                tokio::time::sleep(tokio::time::Duration::from_secs(delay_secs)).await;
            }

            // Check pause after delay
            let is_paused_after_delay = paused_flag.load(Ordering::Relaxed);
            if is_paused_after_delay {
                tracing::info!("⏸️  Paused after rate limit delay, waiting...");
            }

            while paused_flag.load(Ordering::Relaxed) {
                tokio::time::sleep(tokio::time::Duration::from_millis(500)).await;
            }

            if is_paused_after_delay {
                tracing::info!("▶️  Resumed after rate limit delay");
            }
        }
    }

    // 4. EMIT COMPLETION EVENT
    let duration_ms = start_time.elapsed().as_millis() as u64;

    event_emitter.emit_complete(CompleteEvent {
        batch_id: config.batch_id.clone(),
        total_completed: completed,
        total_failed: failed,
        duration_ms,
    });

    tracing::info!(
        "✅ Batch generation completed: {} succeeded, {} failed, {}ms",
        completed,
        failed,
        duration_ms
    );

    Ok(BatchGenerationResult {
        completed,
        failed,
        duration_ms,
    })
}

// =============================================================================
// Helper Functions
// =============================================================================

/// Build module-specific prompt with depth-aware instructions.
///
/// The prompt has two parts:
/// 1. **Header** — module metadata (name, path, files, architecture, exports, code snippets).
///    This is identical for all depth levels.
/// 2. **Instructions** — what sections to generate, how many code examples, and target length.
///    This varies by depth level.
fn build_module_prompt(
    module: &crate::analysis::ModuleAnalysis,
    depth: &DepthLevel,
) -> String {
    let header = build_prompt_header(module);
    let depth_desc = depth_description(depth);
    let instructions = build_depth_instructions(&module.name, depth);

    format!(
        "You are a code documentation expert. Analyze this module and generate {} context documentation.\n\n\
         {}\n\n\
         IMPORTANT: Generate markdown content directly. Do NOT wrap your response in code blocks.\n\n\
         {}",
        depth_desc, header, instructions
    )
}

/// Build the shared metadata header (identical for all depths).
fn build_prompt_header(module: &crate::analysis::ModuleAnalysis) -> String {
    let dependencies = module.architecture.dependencies.join(", ");
    let dependents = module.architecture.dependents.join(", ");
    let external_deps = module.architecture.external_deps.join(", ");

    let exports_str = if !module.symbols.exports.is_empty() {
        module.symbols.exports
            .iter()
            .map(|e| format!("- {} ({})", e.name, e.kind))
            .collect::<Vec<_>>()
            .join("\n")
    } else {
        "(No exports detected by AST analyzer)".to_string()
    };

    format!(
        "MODULE: {}\nPATH: {}\nFILES: {}\n\n\
         ARCHITECTURE:\n\
         - Dependencies: {}\n\
         - Dependents: {}\n\
         - External: {}\n\n\
         EXPORTS (detected by AST analysis):\n{}\n\n\
         CODE SNIPPETS:\n{}",
        module.name,
        module.path,
        module.file_count,
        if dependencies.is_empty() { "none" } else { &dependencies },
        if dependents.is_empty() { "none" } else { &dependents },
        if external_deps.is_empty() { "none" } else { &external_deps },
        exports_str,
        module.code_snippets,
    )
}

/// Human-readable depth description for the prompt preamble.
fn depth_description(depth: &DepthLevel) -> &'static str {
    match depth {
        DepthLevel::Minimal => "brief, concise",
        DepthLevel::Normal => "comprehensive",
        DepthLevel::Detailed => "detailed and thorough",
        DepthLevel::Expert => "expert-level, exhaustive",
    }
}

/// Build depth-specific generation instructions.
fn build_depth_instructions(module_name: &str, depth: &DepthLevel) -> String {
    match depth {
        DepthLevel::Minimal => build_minimal_instructions(module_name),
        DepthLevel::Normal => build_normal_instructions(module_name),
        DepthLevel::Detailed => build_detailed_instructions(module_name),
        DepthLevel::Expert => build_expert_instructions(module_name),
    }
}

/// Minimal: ~500-800 tokens, 0 code examples.
fn build_minimal_instructions(module_name: &str) -> String {
    format!(
        r#"Generate your response following this EXACT structure. Keep it brief and concise (target: 500-800 tokens). Do NOT include code examples.

# {module_name}

> **Quick Summary**: One-sentence description of what this module does

## Purpose

1-2 short paragraphs: what does this module do and why does it exist?

## Key Technologies

Bullet list of main technologies, frameworks, and libraries used.

## API Overview

Brief list of the most important exported functions/types/components (name + one-line description each). Only include the top-level public API.

## Dependencies

- **Internal**: Which project modules does this depend on?
- **External**: Key third-party dependencies

## Notes

Any critical caveats or constraints (1-3 bullets max)."#
    )
}

/// Normal: ~1.5-2K tokens, 1-2 code examples. (≈ original prompt)
fn build_normal_instructions(module_name: &str) -> String {
    format!(
        r#"Generate your response following this EXACT structure (target: 1500-2000 tokens). Include 1-2 concise code examples.

# {module_name}

> **Quick Summary**: One-sentence description of what this module does

## Purpose

2-3 paragraphs explaining:
- What problem does this solve?
- Why does this module exist?
- When should you use it?

## API Reference

### Functions
List exported functions with brief descriptions.

### Types & Interfaces
List exported types and interfaces.

### Components
List React components if applicable.

## Architecture

Explain:
- How does this module fit in the larger system?
- What are its key dependencies?
- What modules depend on it?

## Usage Examples

Provide 1-2 concise usage examples showing the most common use cases.

## Notes

Any important notes or considerations."#
    )
}

/// Detailed: ~3-4K tokens, 3 code examples.
fn build_detailed_instructions(module_name: &str) -> String {
    format!(
        r#"Generate a DETAILED response following this EXACT structure (target: 3000-4000 tokens). Include 3 code examples demonstrating different use cases.

# {module_name}

> **Quick Summary**: One-sentence description of what this module does

## Purpose

2-3 paragraphs explaining:
- What problem does this solve?
- Why does this module exist?
- When should you use it?

## API Reference

### Functions
List all exported functions with descriptions, parameters, and return types.

### Types & Interfaces
List all exported types and interfaces with field descriptions.

### Components
List React components with their props if applicable.

## Architecture

Explain in detail:
- How does this module fit in the larger system?
- What are its key dependencies and why?
- What modules depend on it?
- Internal structure: how are files/submodules organized?

## Data Flow

Describe the main data flow through this module:
- What inputs does it receive?
- How does it process/transform data?
- What outputs does it produce?

## Usage Examples

Provide 3 code examples:
1. Basic usage — simplest use case
2. Common pattern — typical real-world usage
3. Advanced — edge case or complex scenario

## Development Guide

- How to extend or modify this module
- Common patterns to follow when adding new functionality
- Testing approach for this module

## Design Decisions

Key architectural decisions made in this module and their rationale.

## Notes

Important notes, caveats, and known limitations."#
    )
}

/// Expert: ~5-8K tokens, 5 code examples.
fn build_expert_instructions(module_name: &str) -> String {
    format!(
        r#"Generate an EXPERT-LEVEL, exhaustive response following this EXACT structure (target: 5000-8000 tokens). Include 5 detailed code examples.

# {module_name}

> **Quick Summary**: One-sentence description of what this module does

## Purpose

2-3 paragraphs explaining:
- What problem does this solve?
- Why does this module exist?
- When should you use it?

## API Reference

### Functions
List all exported functions with full signatures, descriptions, parameters, return types, and error conditions.

### Types & Interfaces
List all exported types and interfaces with field descriptions and constraints.

### Components
List React components with all props, default values, and usage notes if applicable.

## Architecture

Explain in depth:
- How does this module fit in the larger system?
- What are its key dependencies and why each one is needed?
- What modules depend on it and how?
- Internal structure: how are files/submodules organized?
- Design patterns used (singleton, observer, factory, etc.)

## Data Flow

Describe the complete data flow:
- All inputs, their sources, and validation
- Processing/transformation pipeline step by step
- All outputs, their consumers, and format

## Implementation Analysis

Deep dive into the implementation:
- Core algorithms and their approach
- Key data structures and why they were chosen
- Concurrency/async patterns if applicable
- Error handling strategy

## Algorithm Complexity

For key operations:
- Time complexity (Big-O)
- Space complexity
- Performance characteristics under load

## Performance & Security

- Performance bottlenecks and optimization opportunities
- Security considerations (input validation, access control, data sanitization)
- Resource usage patterns (memory, CPU, I/O)

## State Management

- What state does this module own?
- How is state initialized, updated, and persisted?
- Concurrency safety (locks, atomics, channels)

## Usage Examples

Provide 5 detailed code examples:
1. Basic usage — simplest use case
2. Common pattern — typical real-world usage
3. Advanced — complex scenario
4. Error handling — how to handle failures
5. Integration — using with other modules

## Development Guide

- How to extend or modify this module
- Common patterns to follow when adding new functionality
- Testing approach and test utilities
- Debugging tips

## Design Decisions

Key architectural decisions, alternatives considered, and rationale for choices made.

## Historical Context

- How this module evolved over time
- Major refactors or rewrites
- Lessons learned

## Notes

Important notes, caveats, known limitations, and future improvement opportunities."#
    )
}

/// Build metadata for context file
fn build_metadata(
    module_name: &str,
    model: &str,
    provider: LlmProviderType,
    response: &LlmResponse,
    code_snippets: &str,
) -> ContextMetadata {
    let code_hash = calculate_code_hash(code_snippets);

    ContextMetadata {
        identity: ModuleIdentity {
            name: module_name.to_string(),
            module_type: ModuleType::Feature,
            status: ModuleStatus::Stable,
            owner: None,
            tags: vec![],
        },
        layers: vec![],
        connections: vec![],
        dependencies: Dependencies {
            internal: vec![],
            external: vec![],
            optional: vec![],
        },
        agent_context: None,
        generation: GenerationMetadata {
            analyzed_at: chrono::Utc::now().to_rfc3339(),
            agent: "venore-wizard".to_string(),
            model: model.to_string(),
            provider: provider.as_str().to_string(),
            code_hash: Some(code_hash),
            stale: false,
            tokens_used: response.usage.as_ref().map(|u| u.total_tokens),
            generation_time_ms: None,
        },
    }
}

// =============================================================================
// Tests
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use crate::analysis::{ModuleAnalysis, ModuleArchitecture, ModuleSymbols, SymbolInfo};

    /// Helper: build a ModuleAnalysis with realistic data for testing prompts.
    fn make_test_module() -> ModuleAnalysis {
        ModuleAnalysis {
            name: "auth".to_string(),
            path: "src/auth".to_string(),
            file_count: 5,
            entry_point: Some("index.ts".to_string()),
            architecture: ModuleArchitecture {
                dependencies: vec!["database".to_string(), "config".to_string()],
                dependents: vec!["api".to_string()],
                external_deps: vec!["jsonwebtoken".to_string(), "bcrypt".to_string()],
            },
            symbols: ModuleSymbols {
                exports: vec![
                    SymbolInfo {
                        name: "authenticate".to_string(),
                        kind: "function".to_string(),
                        file: "auth.ts".to_string(),
                        line: 10,
                        exported: true,
                    },
                    SymbolInfo {
                        name: "AuthToken".to_string(),
                        kind: "interface".to_string(),
                        file: "types.ts".to_string(),
                        line: 1,
                        exported: true,
                    },
                ],
                all: vec![],
            },
            imports: vec![],
            code_snippets: "function authenticate(user: string, pass: string): AuthToken { ... }".to_string(),
            files: vec!["auth.ts".to_string(), "types.ts".to_string()],
        }
    }

    /// Helper: build a ModuleAnalysis with empty exports and dependencies.
    fn make_empty_module() -> ModuleAnalysis {
        ModuleAnalysis {
            name: "empty_mod".to_string(),
            path: "src/empty_mod".to_string(),
            file_count: 1,
            entry_point: None,
            architecture: ModuleArchitecture {
                dependencies: vec![],
                dependents: vec![],
                external_deps: vec![],
            },
            symbols: ModuleSymbols {
                exports: vec![],
                all: vec![],
            },
            imports: vec![],
            code_snippets: String::new(),
            files: vec!["mod.rs".to_string()],
        }
    }

    #[test]
    fn test_build_module_prompt_contains_metadata_for_all_depths() {
        let module = make_test_module();

        for depth in &[DepthLevel::Minimal, DepthLevel::Normal, DepthLevel::Detailed, DepthLevel::Expert] {
            let prompt = build_module_prompt(&module, depth);
            assert!(prompt.contains("MODULE: auth"), "depth {:?} missing MODULE", depth);
            assert!(prompt.contains("PATH: src/auth"), "depth {:?} missing PATH", depth);
            assert!(prompt.contains("FILES: 5"), "depth {:?} missing FILES", depth);
            assert!(prompt.contains("database"), "depth {:?} missing dependency", depth);
            assert!(prompt.contains("authenticate (function)"), "depth {:?} missing export", depth);
            assert!(prompt.contains("jsonwebtoken"), "depth {:?} missing external dep", depth);
        }
    }

    #[test]
    fn test_build_module_prompt_minimal_is_concise() {
        let module = make_test_module();
        let prompt = build_module_prompt(&module, &DepthLevel::Minimal);

        assert!(prompt.contains("brief, concise"));
        assert!(prompt.contains("500-800"));
        assert!(prompt.contains("API Overview"));
        assert!(prompt.contains("Key Technologies"));
        // Minimal should NOT contain expert-level sections
        assert!(!prompt.contains("Implementation Analysis"));
        assert!(!prompt.contains("Algorithm Complexity"));
        assert!(!prompt.contains("State Management"));
        assert!(!prompt.contains("Historical Context"));
    }

    #[test]
    fn test_build_module_prompt_normal_has_standard_sections() {
        let module = make_test_module();
        let prompt = build_module_prompt(&module, &DepthLevel::Normal);

        assert!(prompt.contains("comprehensive"));
        assert!(prompt.contains("1500-2000"));
        assert!(prompt.contains("## Purpose"));
        assert!(prompt.contains("## API Reference"));
        assert!(prompt.contains("## Architecture"));
        assert!(prompt.contains("## Usage Examples"));
        assert!(prompt.contains("1-2 concise"));
    }

    #[test]
    fn test_build_module_prompt_detailed_has_extra_sections() {
        let module = make_test_module();
        let prompt = build_module_prompt(&module, &DepthLevel::Detailed);

        assert!(prompt.contains("DETAILED"));
        assert!(prompt.contains("3000-4000"));
        assert!(prompt.contains("3 code examples"));
        assert!(prompt.contains("## Data Flow"));
        assert!(prompt.contains("## Development Guide"));
        assert!(prompt.contains("## Design Decisions"));
    }

    #[test]
    fn test_build_module_prompt_expert_has_all_sections() {
        let module = make_test_module();
        let prompt = build_module_prompt(&module, &DepthLevel::Expert);

        assert!(prompt.contains("EXPERT-LEVEL"));
        assert!(prompt.contains("5000-8000"));
        assert!(prompt.contains("5 detailed"));
        assert!(prompt.contains("## Implementation Analysis"));
        assert!(prompt.contains("## Algorithm Complexity"));
        assert!(prompt.contains("## Performance & Security"));
        assert!(prompt.contains("## State Management"));
        assert!(prompt.contains("## Historical Context"));
    }

    #[test]
    fn test_build_module_prompt_length_increases_with_depth() {
        let module = make_test_module();

        let minimal = build_module_prompt(&module, &DepthLevel::Minimal);
        let normal = build_module_prompt(&module, &DepthLevel::Normal);
        let detailed = build_module_prompt(&module, &DepthLevel::Detailed);
        let expert = build_module_prompt(&module, &DepthLevel::Expert);

        assert!(
            minimal.len() < normal.len(),
            "minimal ({}) should be shorter than normal ({})",
            minimal.len(), normal.len()
        );
        assert!(
            normal.len() < detailed.len(),
            "normal ({}) should be shorter than detailed ({})",
            normal.len(), detailed.len()
        );
        assert!(
            detailed.len() < expert.len(),
            "detailed ({}) should be shorter than expert ({})",
            detailed.len(), expert.len()
        );
    }

    #[test]
    fn test_build_module_prompt_empty_exports() {
        let module = make_empty_module();
        let prompt = build_module_prompt(&module, &DepthLevel::Normal);

        assert!(prompt.contains("No exports detected by AST analyzer"));
    }

    #[test]
    fn test_build_module_prompt_empty_dependencies() {
        let module = make_empty_module();
        let prompt = build_module_prompt(&module, &DepthLevel::Normal);

        assert!(prompt.contains("Dependencies: none"));
        assert!(prompt.contains("Dependents: none"));
        assert!(prompt.contains("External: none"));
    }
}
